/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import { V2 } from "../resources/v2/client/Client.js";

export declare namespace Beta {
    export interface Options {
        environment?: core.Supplier<environments.ImageKitEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Beta {
    protected readonly _options: Beta.Options;
    protected _v2: V2 | undefined;

    constructor(_options: Beta.Options) {
        this._options = _options;
    }

    public get v2(): V2 {
        return (this._v2 ??= new V2(this._options));
    }
}
