/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BulkRemoveAiTagsResponse {
    /** An array of fileIds that in which AITags were successfully removed. */
    successfullyUpdatedFileIds?: string[];
}
