/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BulkDeleteResponse {
    /** An array of fileIds that were successfully deleted. */
    successfullyDeletedFileIds?: string[];
}
