/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BulkRemoveTagsResponse {
    /** An array of fileIds that in which tags were successfully removed. */
    successfullyUpdatedFileIds?: string[];
}
