/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BulkAddTagsResponse {
    /** An array of fileIds that in which tags were successfully added. */
    successfullyUpdatedFileIds?: string[];
}
