/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssetsListRequestFileType = "all" | "image" | "non-image";
export const AssetsListRequestFileType = {
    All: "all",
    Image: "image",
    NonImage: "non-image",
} as const;
