/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssetsListRequestType = "file" | "file-version" | "folder" | "all";
export const AssetsListRequestType = {
    File: "file",
    FileVersion: "file-version",
    Folder: "folder",
    All: "all",
} as const;
