/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AssetsListRequestSort =
    | "ASC_NAME"
    | "DESC_NAME"
    | "ASC_CREATED"
    | "DESC_CREATED"
    | "ASC_UPDATED"
    | "DESC_UPDATED"
    | "ASC_HEIGHT"
    | "DESC_HEIGHT"
    | "ASC_WIDTH"
    | "DESC_WIDTH"
    | "ASC_SIZE"
    | "DESC_SIZE"
    | "ASC_RELEVANCE"
    | "DESC_RELEVANCE";
export const AssetsListRequestSort = {
    AscName: "ASC_NAME",
    DescName: "DESC_NAME",
    AscCreated: "ASC_CREATED",
    DescCreated: "DESC_CREATED",
    AscUpdated: "ASC_UPDATED",
    DescUpdated: "DESC_UPDATED",
    AscHeight: "ASC_HEIGHT",
    DescHeight: "DESC_HEIGHT",
    AscWidth: "ASC_WIDTH",
    DescWidth: "DESC_WIDTH",
    AscSize: "ASC_SIZE",
    DescSize: "DESC_SIZE",
    AscRelevance: "ASC_RELEVANCE",
    DescRelevance: "DESC_RELEVANCE",
} as const;
