/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../../../environments.js";
import * as core from "../../../../../../core/index.js";
import { Files } from "../resources/files/client/Client.js";

export declare namespace V2 {
    export interface Options {
        environment?: core.Supplier<environments.ImageKitEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class V2 {
    protected readonly _options: V2.Options;
    protected _files: Files | undefined;

    constructor(_options: V2.Options) {
        this._options = _options;
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }
}
