configured_endpoints: 42
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/imagekit-inc%2Fimagekit-1499148ce5fc81b4d8c8b3eaadf7adfaf54df5fa0b3a0452c3f5ef0dfe884a95.yml
openapi_spec_hash: e91526b143d3e696bef2b4d0ea3aa2b4
config_hash: e42d7fc3a8c92c35099cc283f9a4467a
