/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CustomMetadataFieldsListRequest {
    /** Set it to `true` to include deleted field objects in the API response. */
    includeDeleted?: boolean;
}
