/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index.js";
import * as core from "../../core/index.js";

export class LockedError extends errors.ImageKitError {
    constructor(body?: unknown, rawResponse?: core.RawResponse) {
        super({
            message: "LockedError",
            statusCode: 423,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, LockedError.prototype);
    }
}
