/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InvalidationCreateResponse {
    /** Unique identifier of the purge request. This can be used to check the status of the purge request. */
    requestId?: string;
}
