/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InvalidationGetResponse {
    /** Status of the purge request. */
    status?: InvalidationGetResponse.Status;
}

export namespace InvalidationGetResponse {
    /**
     * Status of the purge request.
     */
    export type Status = "Pending" | "Completed";
    export const Status = {
        Pending: "Pending",
        Completed: "Completed",
    } as const;
}
