/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { ImageKitClient } from "../../../src/Client";

describe("Usage", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ImageKitClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = {
            bandwidthBytes: 21991583578,
            mediaLibraryStorageBytes: 1878758298,
            videoProcessingUnitsCount: 0,
            extensionUnitsCount: 0,
            originalCacheStorageBytes: 0,
        };
        server.mockEndpoint().get("/v1/accounts/usage").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.accounts.usage.get({
            startDate: "startDate",
            endDate: "endDate",
        });
        expect(response).toEqual({
            bandwidthBytes: 21991583578,
            mediaLibraryStorageBytes: 1878758298,
            videoProcessingUnitsCount: 0,
            extensionUnitsCount: 0,
            originalCacheStorageBytes: 0,
        });
    });
});
