// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'imagekit-api-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import ImageKit from '@imagekit/nodejs';

export const metadata: Metadata = {
  resource: 'accounts.urlEndpoints',
  operation: 'write',
  tags: [],
  httpMethod: 'delete',
  httpPath: '/v1/accounts/url-endpoints/{id}',
  operationId: 'delete-url-endpoint',
};

export const tool: Tool = {
  name: 'delete_accounts_url_endpoints',
  description:
    '**Note:** This API is currently in beta.  \nDeletes the URL‑endpoint identified by `id`. You cannot delete the default URL‑endpoint created by ImageKit during account creation.\n',
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
        description:
          'Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.',
      },
    },
    required: ['id'],
  },
  annotations: {
    idempotentHint: true,
  },
};

export const handler = async (client: ImageKit, args: Record<string, unknown> | undefined) => {
  const { id, ...body } = args as any;
  const response = await client.accounts.urlEndpoints.delete(id).asResponse();
  return asTextContentResult(await response.text());
};

export default { metadata, tool, handler };
