/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import { Invalidation } from "../resources/invalidation/client/Client.js";

export declare namespace Cache {
    export interface Options {
        environment?: core.Supplier<environments.ImageKitEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Cache {
    protected readonly _options: Cache.Options;
    protected _invalidation: Invalidation | undefined;

    constructor(_options: Cache.Options) {
        this._options = _options;
    }

    public get invalidation(): Invalidation {
        return (this._invalidation ??= new Invalidation(this._options));
    }
}
