/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fileIds: ["598821f949c0a938d57563bd", "598821f949c0a938d57563be"],
 *         AITags: ["t-shirt", "round-neck", "sale2019"]
 *     }
 */
export interface BulkRemoveAiTagsRequest {
    /** An array of fileIds from which you want to remove AITags. */
    fileIds: string[];
    /** An array of AITags that you want to remove from the files. */
    AITags: string[];
}
