/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fileIds: ["598821f949c0a938d57563bd", "598821f949c0a938d57563be"],
 *         tags: ["t-shirt", "round-neck", "sale2019"]
 *     }
 */
export interface BulkAddTagsRequest {
    /** An array of fileIds to which you want to add tags. */
    fileIds: string[];
    /** An array of tags that you want to add to the files. */
    tags: string[];
}
