/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fileIds: ["598821f949c0a938d57563bd", "598821f949c0a938d57563be"]
 *     }
 */
export interface BulkDeleteRequest {
    /** An array of fileIds which you want to delete. */
    fileIds: string[];
}
