/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../../../index.js";

export interface FilesUpdateResponse extends ImageKit.FileDetails {
    extensionStatus?: FilesUpdateResponse.ExtensionStatus;
}

export namespace FilesUpdateResponse {
    export interface ExtensionStatus {
        "google-auto-tagging"?: ExtensionStatus.GoogleAutoTagging;
        "aws-auto-tagging"?: ExtensionStatus.AwsAutoTagging;
        "remove-bg"?: ExtensionStatus.RemoveBg;
        "ai-auto-description"?: ExtensionStatus.AiAutoDescription;
    }

    export namespace ExtensionStatus {
        export type GoogleAutoTagging = "success" | "pending" | "failed";
        export const GoogleAutoTagging = {
            Success: "success",
            Pending: "pending",
            Failed: "failed",
        } as const;
        export type AwsAutoTagging = "success" | "pending" | "failed";
        export const AwsAutoTagging = {
            Success: "success",
            Pending: "pending",
            Failed: "failed",
        } as const;
        export type RemoveBg = "success" | "pending" | "failed";
        export const RemoveBg = {
            Success: "success",
            Pending: "pending",
            Failed: "failed",
        } as const;
        export type AiAutoDescription = "success" | "pending" | "failed";
        export const AiAutoDescription = {
            Success: "success",
            Pending: "pending",
            Failed: "failed",
        } as const;
    }
}
