/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../../../index.js";

export type FilesUpdateRequest =
    | {
          removeAITags?: (string[] | "all") | undefined;
          webhookUrl?: string | undefined;
          extensions?:
              | (ImageKit.RemovedotBgExtension | ImageKit.AutoTaggingExtension | ImageKit.AutoDescriptionExtension)[]
              | undefined;
          tags?: string[] | undefined;
          customCoordinates?: string | undefined;
          customMetadata?: Record<string, unknown> | undefined;
          description?: string | undefined;
      }
    | {
          publish?:
              | {
                    isPublished: boolean;
                    includeFileVersions?: boolean | undefined;
                }
              | undefined;
      };
