/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface JobGetResponse {
    /** Unique identifier of the bulk job. */
    jobId?: string;
    /** Type of the bulk job. Possible values - `COPY_FOLDER`, `MOVE_FOLDER`, `RENAME_FOLDER`. */
    type?: string;
    /** Status of the bulk job. Possible values - `Pending`, `Completed`. */
    status?: string;
    /** Unique identifier of the purge request. This will be present only if `purgeCache` is set to `true` in the rename folder API request. */
    purgeRequestId?: string;
}
