/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AutoDescriptionExtension {
    /** Specifies the auto description extension. */
    name: "ai-auto-description";
}
