/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AutoTaggingExtension {
    /** Specifies the auto-tagging extension used. */
    name: AutoTaggingExtension.Name;
    /** Minimum confidence level for tags to be considered valid. */
    minConfidence: number;
    /** Maximum number of tags to attach to the asset. */
    maxTags: number;
}

export namespace AutoTaggingExtension {
    /**
     * Specifies the auto-tagging extension used.
     */
    export type Name = "google-auto-tagging" | "aws-auto-tagging";
    export const Name = {
        GoogleAutoTagging: "google-auto-tagging",
        AwsAutoTagging: "aws-auto-tagging",
    } as const;
}
