/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing Exif details.
 */
export interface ExifDetails {
    ExposureTime?: number;
    FNumber?: number;
    ExposureProgram?: number;
    ISO?: number;
    ExifVersion?: string;
    DateTimeOriginal?: string;
    CreateDate?: string;
    ShutterSpeedValue?: number;
    ApertureValue?: number;
    ExposureCompensation?: number;
    MeteringMode?: number;
    Flash?: number;
    FocalLength?: number;
    SubSecTime?: string;
    FlashpixVersion?: string;
    ColorSpace?: number;
    ExifImageWidth?: number;
    ExifImageHeight?: number;
    InteropOffset?: number;
    FocalPlaneXResolution?: number;
    FocalPlaneYResolution?: number;
    FocalPlaneResolutionUnit?: number;
    CustomRendered?: number;
    ExposureMode?: number;
    WhiteBalance?: number;
    SceneCaptureType?: number;
}
