/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing EXIF image information.
 */
export interface ExifImage {
    Make?: string;
    Model?: string;
    Orientation?: number;
    XResolution?: number;
    YResolution?: number;
    ResolutionUnit?: number;
    Software?: string;
    ModifyDate?: string;
    YCbCrPositioning?: number;
    ExifOffset?: number;
    GPSInfo?: number;
}
