/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Folder {
    /** Type of the asset. */
    type?: "folder";
    /** Unique identifier of the asset. */
    folderId?: string;
    /** Name of the asset. */
    name?: string;
    /** Path of the folder. This is the path you would use in the URL to access the folder. For example, if the folder is at the root of the media library, the path will be /folder. If the folder is inside another folder named images, the path will be /images/folder. */
    folderPath?: string;
    /** Date and time when the folder was created. The date and time is in ISO8601 format. */
    createdAt?: string;
    /** Date and time when the folder was last updated. The date and time is in ISO8601 format. */
    updatedAt?: string;
}
