/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

/**
 * JSON object containing metadata.
 */
export interface Metadata {
    /** The height of the image or video in pixels. */
    height?: number;
    /** The width of the image or video in pixels. */
    width?: number;
    /** The file size in bytes. */
    size?: number;
    /** The format of the file (e.g., 'jpg', 'mp4'). */
    format?: string;
    /** Indicates if the image has a color profile. */
    hasColorProfile?: boolean;
    /** The quality indicator of the image. */
    quality?: number;
    /** The density of the image in DPI. */
    density?: number;
    /** Indicates if the image contains transparent areas. */
    hasTransparency?: boolean;
    /** Perceptual hash of the image. */
    pHash?: string;
    /** The bit rate of the video in kbps (only for video). */
    bitRate?: number;
    /** The duration of the video in seconds (only for video). */
    duration?: number;
    /** The audio codec used in the video (only for video). */
    audioCodec?: string;
    /** The video codec used in the video (only for video). */
    videoCodec?: string;
    exif?: Metadata.Exif;
}

export namespace Metadata {
    export interface Exif {
        image?: ImageKit.ExifImage;
        thumbnail?: ImageKit.Thumbnail;
        exif?: ImageKit.ExifDetails;
        gps?: ImageKit.Gps;
        interoperability?: ImageKit.Interoperability;
        makernote?: Record<string, unknown>;
    }
}
