/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

/**
 * Origin object as returned by the API (sensitive fields removed).
 */
export type OriginResponse =
    | ImageKit.OriginResponse.S3
    | ImageKit.OriginResponse.S3Compatible
    | ImageKit.OriginResponse.CloudinaryBackup
    | ImageKit.OriginResponse.WebFolder
    | ImageKit.OriginResponse.WebProxy
    | ImageKit.OriginResponse.Gcs
    | ImageKit.OriginResponse.AzureBlob
    | ImageKit.OriginResponse.AkeneoPim;

export namespace OriginResponse {
    export interface S3 {
        type: "S3";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        /** S3 bucket name. */
        bucket: string;
        prefix?: unknown;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface S3Compatible {
        type: "S3_COMPATIBLE";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        /** S3 bucket name. */
        bucket: string;
        prefix?: unknown;
        /** Custom S3-compatible endpoint. */
        endpoint: string;
        /** Use path-style S3 URLs? */
        s3ForcePathStyle: boolean;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface CloudinaryBackup {
        type: "CLOUDINARY_BACKUP";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        /** S3 bucket name. */
        bucket: string;
        prefix?: unknown;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface WebFolder {
        type: "WEB_FOLDER";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        baseUrl?: unknown;
        /** Forward the Host header to origin? */
        forwardHostHeaderToOrigin: boolean;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface WebProxy {
        type: "WEB_PROXY";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface Gcs {
        type: "GCS";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        bucket: string;
        prefix?: unknown;
        clientEmail: string;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface AzureBlob {
        type: "AZURE_BLOB";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        container: string;
        prefix?: unknown;
        accountName: string;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }

    export interface AkeneoPim {
        type: "AKENEO_PIM";
        /** Display name of the origin. */
        name: string;
        /** Whether to send a Canonical header. */
        includeCanonicalHeader: boolean;
        /** URL used in the Canonical header (if enabled). */
        baseUrlForCanonicalHeader?: string;
        baseUrl?: unknown;
        /** Unique identifier for the origin. This is generated by ImageKit when you create a new origin. */
        id?: string;
    }
}
