/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RemovedotBgExtension {
    /** Specifies the background removal extension. */
    name: "remove-bg";
    options?: RemovedotBgExtension.Options;
}

export namespace RemovedotBgExtension {
    export interface Options {
        /** Whether to add an artificial shadow to the result. Default is false. Note: Adding shadows is currently only supported for car photos. */
        add_shadow?: boolean;
        /** Allows semi-transparent regions in the result. Default is true. Note: Semitransparency is currently only supported for car windows. */
        semitransparency?: boolean;
        /** Specifies a solid color background using hex code (e.g., "81d4fa", "fff") or color name (e.g., "green"). If this parameter is set, `bg_image_url` must be empty. */
        bg_color?: string;
        /** Sets a background image from a URL. If this parameter is set, `bg_color` must be empty. */
        bg_image_url?: string;
    }
}
