/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object containing Thumbnail information.
 */
export interface Thumbnail {
    Compression?: number;
    XResolution?: number;
    YResolution?: number;
    ResolutionUnit?: number;
    ThumbnailOffset?: number;
    ThumbnailLength?: number;
}
