/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TooManyRequestsErrorBody {
    /** A description of the error, providing details about why the rate limit has been exceeded. */
    message?: string;
}
