/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

export type TransformationObjectPostItem =
    | ImageKit.TransformationObjectPostItem.Transformation
    | ImageKit.TransformationObjectPostItem.GifToVideo
    | ImageKit.TransformationObjectPostItem.Thumbnail
    | ImageKit.TransformationObjectPostItem.Abs;

export namespace TransformationObjectPostItem {
    export interface Transformation {
        type: "transformation";
        /**
         * Transformation string (e.g. `w-200,h-200`).
         * Same syntax as ImageKit URL-based transformations.
         */
        value: string;
    }

    export interface GifToVideo {
        type: "gif-to-video";
        /**
         * Optional transformation string to apply to the output video.
         * **Example**: `q-80`
         */
        value?: string;
    }

    export interface Thumbnail {
        type: "thumbnail";
        /**
         * Optional transformation string.
         * **Example**: `w-150,h-150`
         */
        value?: string;
    }

    export interface Abs {
        type: "abs";
        /** List of different representations you want to create separated by an underscore. */
        value: string;
        /** Streaming protocol to use (`hls` or `dash`). */
        protocol: TransformationObjectPostItemAbs.Protocol;
    }

    export namespace TransformationObjectPostItemAbs {
        /**
         * Streaming protocol to use (`hls` or `dash`).
         */
        export type Protocol = "hls" | "dash";
        export const Protocol = {
            Hls: "hls",
            Dash: "dash",
        } as const;
    }
}
