/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

/**
 * Schema for URL endpoint resource.
 */
export interface UrlEndpointSchema {
    /** Description of the URL endpoint. */
    description: string;
    /** Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint). */
    urlPrefix?: string;
    /** Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint. */
    origins?: string[];
    /** Configuration for third-party URL rewriting. */
    urlRewriter?: ImageKit.UrlEndpointSchemaUrlRewriter;
}
