/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

/**
 * Configuration for third-party URL rewriting.
 */
export type UrlEndpointResponseUrlRewriter =
    | ImageKit.UrlEndpointResponseUrlRewriter.Cloudinary
    | ImageKit.UrlEndpointResponseUrlRewriter.Imgix
    | ImageKit.UrlEndpointResponseUrlRewriter.Akamai;

export namespace UrlEndpointResponseUrlRewriter {
    export interface Cloudinary {
        type: "CLOUDINARY";
        /** Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL. */
        preserveAssetDeliveryTypes: boolean;
    }

    export interface Imgix {
        type: "IMGIX";
    }

    export interface Akamai {
        type: "AKAMAI";
    }
}
