/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

/**
 * URL‑endpoint object as returned by the API.
 */
export interface UrlEndpointResponse {
    /** Description of the URL endpoint. */
    description: string;
    /** Path segment appended to your base URL to form the endpoint (letters, digits, and hyphens only — or empty for the default endpoint). */
    urlPrefix: string;
    /** Ordered list of origin IDs to try when the file isn’t in the Media Library; ImageKit checks them in the sequence provided. Origin must be created before it can be used in a URL endpoint. */
    origins: string[];
    /** Configuration for third-party URL rewriting. */
    urlRewriter?: ImageKit.UrlEndpointResponseUrlRewriter;
    /** Unique identifier for the URL-endpoint. This is generated by ImageKit when you create a new URL-endpoint. For the default URL-endpoint, this is always `default`. */
    id?: string;
}
