/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

/**
 * Configuration for third-party URL rewriting.
 */
export type UrlEndpointSchemaUrlRewriter =
    | ImageKit.UrlEndpointSchemaUrlRewriter.Cloudinary
    | ImageKit.UrlEndpointSchemaUrlRewriter.Imgix
    | ImageKit.UrlEndpointSchemaUrlRewriter.Akamai;

export namespace UrlEndpointSchemaUrlRewriter {
    export interface Cloudinary {
        type: "CLOUDINARY";
        /** Whether to preserve `<asset_type>/<delivery_type>` in the rewritten URL. */
        preserveAssetDeliveryTypes?: boolean;
    }

    export interface Imgix {
        type: "IMGIX";
    }

    export interface Akamai {
        type: "AKAMAI";
    }
}
