/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VideoTransformationOptions {
    video_codec?: VideoTransformationOptions.VideoCodec;
    audio_codec?: VideoTransformationOptions.AudioCodec;
    auto_rotate?: boolean;
    quality?: number;
    format?: VideoTransformationOptions.Format;
    stream_protocol?: VideoTransformationOptions.StreamProtocol;
    variants?: string[];
}

export namespace VideoTransformationOptions {
    export type VideoCodec = "h264" | "vp9";
    export const VideoCodec = {
        H264: "h264",
        Vp9: "vp9",
    } as const;
    export type AudioCodec = "aac" | "opus";
    export const AudioCodec = {
        Aac: "aac",
        Opus: "opus",
    } as const;
    export type Format = "mp4" | "webm" | "jpg" | "png" | "webp";
    export const Format = {
        Mp4: "mp4",
        Webm: "webm",
        Jpg: "jpg",
        Png: "png",
        Webp: "webp",
    } as const;
    export type StreamProtocol = "HLS" | "DASH";
    export const StreamProtocol = {
        Hls: "HLS",
        Dash: "DASH",
    } as const;
}
