/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VideoWebhookRequestInfo {
    /** Unique ID for the originating request. */
    x_request_id: string;
    /** URL of the submitted request. */
    url: string;
    /** User-Agent header of the originating request. */
    user_agent?: string;
}
