/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

export interface VideoTransformationBase {
    type: VideoTransformationBase.Type;
    options?: ImageKit.VideoTransformationOptions;
}

export namespace VideoTransformationBase {
    export type Type = "video-transformation" | "gif-to-video" | "video-thumbnail";
    export const Type = {
        VideoTransformation: "video-transformation",
        GifToVideo: "gif-to-video",
        VideoThumbnail: "video-thumbnail",
    } as const;
}
