/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

export interface VideoTransformationReadyEvent {
    type: "video.transformation.ready";
    /** Unique identifier for the event. */
    id: string;
    created_at: string;
    request: ImageKit.VideoWebhookRequestInfo;
    timings?: VideoTransformationReadyEvent.Timings;
    data: VideoTransformationReadyEvent.Data;
}

export namespace VideoTransformationReadyEvent {
    export interface Timings {
        /** Milliseconds spent downloading the source. */
        download_duration?: number;
        /** Milliseconds spent encoding. */
        encoding_duration?: number;
    }

    export interface Data {
        asset: ImageKit.VideoAsset;
        transformation: Data.Transformation;
    }

    export namespace Data {
        export interface Transformation extends ImageKit.VideoTransformationBase {
            output?: Transformation.Output;
        }

        export namespace Transformation {
            export interface Output {
                url: string;
                video_metadata?: Output.VideoMetadata;
            }

            export namespace Output {
                export interface VideoMetadata {
                    duration: number;
                    width: number;
                    height: number;
                    bitrate: number;
                }
            }
        }
    }
}
