/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

export interface VideoTransformationErrorEvent {
    type: "video.transformation.error";
    /** Unique identifier for the event. */
    id: string;
    created_at: string;
    request: ImageKit.VideoWebhookRequestInfo;
    data: VideoTransformationErrorEvent.Data;
}

export namespace VideoTransformationErrorEvent {
    export interface Data {
        asset: ImageKit.VideoAsset;
        transformation: Data.Transformation;
    }

    export namespace Data {
        export interface Transformation extends ImageKit.VideoTransformationBase {
            error?: Transformation.Error_;
        }

        export namespace Transformation {
            export interface Error_ {
                reason: Error_.Reason;
            }

            export namespace Error_ {
                export type Reason = "encoding_failed" | "download_failed" | "internal_server_error";
                export const Reason = {
                    EncodingFailed: "encoding_failed",
                    DownloadFailed: "download_failed",
                    InternalServerError: "internal_server_error",
                } as const;
            }
        }
    }
}
