/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ImageKit from "../index.js";

export interface VideoTransformationAcceptedEvent {
    type: "video.transformation.accepted";
    /** Unique identifier for the event. */
    id: string;
    created_at: string;
    request: ImageKit.VideoWebhookRequestInfo;
    data: VideoTransformationAcceptedEvent.Data;
}

export namespace VideoTransformationAcceptedEvent {
    export interface Data {
        asset: ImageKit.VideoAsset;
        transformation: ImageKit.VideoTransformationBase;
    }
}
