/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "url"
 *     }
 *
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface MetadataGetFromUrlRequest {
    /** Should be a valid file URL. It should be accessible using your ImageKit.io account. */
    url: string;
}
