/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { ImageKitClient } from "../../../src/Client";

describe("Job", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new ImageKitClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = {
            jobId: "5d5b1a9b4c8c4c0001f3e4a2",
            type: "COPY_FOLDER",
            status: "Completed",
            purgeRequestId: "purgeRequestId",
        };
        server.mockEndpoint().get("/v1/bulkJobs/jobId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.folders.job.get("jobId");
        expect(response).toEqual({
            jobId: "5d5b1a9b4c8c4c0001f3e4a2",
            type: "COPY_FOLDER",
            status: "Completed",
            purgeRequestId: "purgeRequestId",
        });
    });
});
