/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         sourceFolderPath: "/path/of/source/folder",
 *         destinationPath: "/path/of/destination/folder"
 *     }
 */
export interface FoldersCopyRequest {
    /** The full path to the source folder you want to copy. */
    sourceFolderPath: string;
    /** Full path to the destination folder where you want to copy the source folder into. */
    destinationPath: string;
    /** Option to copy all versions of files that are nested inside the selected folder. By default, only the current version of each file will be copied. When set to true, all versions of each file will be copied. Default value - `false`. */
    includeVersions?: boolean;
}
