/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         sourceFolderPath: "/path/of/source/folder",
 *         destinationPath: "/path/of/destination/folder"
 *     }
 */
export interface FoldersMoveRequest {
    /** The full path to the source folder you want to move. */
    sourceFolderPath: string;
    /** Full path to the destination folder where you want to move the source folder into. */
    destinationPath: string;
}
