/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         folderPath: "/folder/to/delete/"
 *     }
 */
export interface FoldersDeleteRequest {
    /** Full path to the folder you want to delete. For example `/folder/to/delete/`. */
    folderPath: string;
}
