/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UsageGetResponse {
    /** Amount of bandwidth used in bytes. */
    bandwidthBytes?: number;
    /** Storage used by media library in bytes. */
    mediaLibraryStorageBytes?: number;
    /** Number of video processing units used. */
    videoProcessingUnitsCount?: number;
    /** Number of extension units used. */
    extensionUnitsCount?: number;
    /** Storage used by the original cache in bytes. */
    originalCacheStorageBytes?: number;
}
