/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         sourceFilePath: "/path/to/file.jpg",
 *         destinationPath: "/folder/to/copy/into/"
 *     }
 */
export interface FilesCopyRequest {
    /** The full path of the file you want to copy. */
    sourceFilePath: string;
    /** Full path to the folder you want to copy the above file into. */
    destinationPath: string;
    /** Option to copy all versions of a file. By default, only the current version of the file is copied. When set to true, all versions of the file will be copied. Default value - `false`. */
    includeFileVersions?: boolean;
}
