/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         sourceFilePath: "/path/to/file.jpg",
 *         destinationPath: "/folder/to/move/into/"
 *     }
 */
export interface FilesMoveRequest {
    /** The full path of the file you want to move. */
    sourceFilePath: string;
    /** Full path to the folder you want to move the above file into. */
    destinationPath: string;
}
