/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         startDate: "startDate",
 *         endDate: "endDate"
 *     }
 */
export interface UsageGetRequest {
    /** Specify a `startDate` in `YYYY-MM-DD` format. It should be before the `endDate`. The difference between `startDate` and `endDate` should be less than 90 days. */
    startDate: string;
    /** Specify a `endDate` in `YYYY-MM-DD` format. It should be after the `startDate`. The difference between `startDate` and `endDate` should be less than 90 days. */
    endDate: string;
}
