/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { ImageKitClient } from "../../src/Client";

describe("Assets", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new ImageKitClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                fileId: "598821f949c0a938d57563bd",
                type: "file",
                name: "file.jpg",
                filePath: "/images/products/file.jpg",
                tags: ["t-shirt", "round-neck", "sale2019"],
                AITags: [
                    { name: "Shirt", confidence: 90.12, source: "google-auto-tagging" },
                    { name: "T-shirt", confidence: 80.12, source: "aws-auto-tagging" },
                ],
                versionInfo: { id: "598821f949c0a938d57563bd", name: "Version 2" },
                isPrivateFile: false,
                isPublished: true,
                url: "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?updatedAt=1566630881313",
                thumbnail:
                    "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?updatedAt=1566630881313&tr=n-ik_ml_thumbnail",
                fileType: "image",
                mime: "image/jpeg",
                width: 100,
                height: 100,
                size: 100,
                hasAlpha: false,
                customMetadata: { brand: "Nike", color: "red" },
                createdAt: "2019-08-24T06:14:41.313Z",
                updatedAt: "2019-08-24T06:14:41.313Z",
            },
            {
                fileId: "598821f949c0a938d81963bd",
                type: "file-version",
                name: "file.jpg",
                filePath: "/images/products/file.jpg",
                tags: ["t-shirt", "sale2019"],
                AITags: [
                    { name: "Shirt", confidence: 90.12, source: "google-auto-tagging" },
                    { name: "T-shirt", confidence: 80.12, source: "aws-auto-tagging" },
                ],
                versionInfo: { id: "598821f949c0a938d57563bd", name: "Version 1" },
                isPrivateFile: false,
                isPublished: true,
                url: "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?ik-obj-version=iAg8gxkqo_QUBwqNeQrJzuyce2XB7Gc4&updatedAt=1566630881313",
                thumbnail:
                    "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?ik-obj-version=iAg8gxkqo_QUBwqNeQrJzuyce2XB7Gc4&updatedAt=1566630881313&tr=n-ik_ml_thumbnail",
                fileType: "image",
                mime: "image/jpeg",
                width: 100,
                height: 100,
                size: 100,
                hasAlpha: false,
                customMetadata: { brand: "Nike", color: "red" },
                createdAt: "2019-08-24T06:15:41.313Z",
                updatedAt: "2019-08-24T06:15:41.313Z",
            },
            {
                type: "folder",
                folderId: "6441fce4e809dd54b0dee029",
                name: "summer",
                folderPath: "/sale",
                createdAt: "2023-04-21T03:03:00.869Z",
                updatedAt: "2023-04-21T03:10:22.374Z",
            },
        ];
        server.mockEndpoint().get("/v1/files").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.assets.list();
        expect(response).toEqual([
            {
                fileId: "598821f949c0a938d57563bd",
                type: "file",
                name: "file.jpg",
                filePath: "/images/products/file.jpg",
                tags: ["t-shirt", "round-neck", "sale2019"],
                AITags: [
                    {
                        name: "Shirt",
                        confidence: 90.12,
                        source: "google-auto-tagging",
                    },
                    {
                        name: "T-shirt",
                        confidence: 80.12,
                        source: "aws-auto-tagging",
                    },
                ],
                versionInfo: {
                    id: "598821f949c0a938d57563bd",
                    name: "Version 2",
                },
                isPrivateFile: false,
                isPublished: true,
                url: "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?updatedAt=1566630881313",
                thumbnail:
                    "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?updatedAt=1566630881313&tr=n-ik_ml_thumbnail",
                fileType: "image",
                mime: "image/jpeg",
                width: 100,
                height: 100,
                size: 100,
                hasAlpha: false,
                customMetadata: {
                    brand: "Nike",
                    color: "red",
                },
                createdAt: "2019-08-24T06:14:41.313Z",
                updatedAt: "2019-08-24T06:14:41.313Z",
            },
            {
                fileId: "598821f949c0a938d81963bd",
                type: "file-version",
                name: "file.jpg",
                filePath: "/images/products/file.jpg",
                tags: ["t-shirt", "sale2019"],
                AITags: [
                    {
                        name: "Shirt",
                        confidence: 90.12,
                        source: "google-auto-tagging",
                    },
                    {
                        name: "T-shirt",
                        confidence: 80.12,
                        source: "aws-auto-tagging",
                    },
                ],
                versionInfo: {
                    id: "598821f949c0a938d57563bd",
                    name: "Version 1",
                },
                isPrivateFile: false,
                isPublished: true,
                url: "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?ik-obj-version=iAg8gxkqo_QUBwqNeQrJzuyce2XB7Gc4&updatedAt=1566630881313",
                thumbnail:
                    "https://ik.imagekit.io/your_imagekit_id/images/products/file.jpg?ik-obj-version=iAg8gxkqo_QUBwqNeQrJzuyce2XB7Gc4&updatedAt=1566630881313&tr=n-ik_ml_thumbnail",
                fileType: "image",
                mime: "image/jpeg",
                width: 100,
                height: 100,
                size: 100,
                hasAlpha: false,
                customMetadata: {
                    brand: "Nike",
                    color: "red",
                },
                createdAt: "2019-08-24T06:15:41.313Z",
                updatedAt: "2019-08-24T06:15:41.313Z",
            },
            {
                type: "folder",
                folderId: "6441fce4e809dd54b0dee029",
                name: "summer",
                folderPath: "/sale",
                createdAt: "2023-04-21T03:03:00.869Z",
                updatedAt: "2023-04-21T03:10:22.374Z",
            },
        ]);
    });
});
