/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         url: "https://ik.imagekit.io/your_imagekit_id/default-image.jpg"
 *     }
 */
export interface InvalidationCreateRequest {
    /** The full URL of the file to be purged. */
    url: string;
}
