/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { Files } from "./api/resources/files/client/Client.js";
import { CustomMetadataFields } from "./api/resources/customMetadataFields/client/Client.js";
import { Assets } from "./api/resources/assets/client/Client.js";
import { Folders } from "./api/resources/folders/client/Client.js";
import { Accounts } from "./api/resources/accounts/client/Client.js";
import { Beta } from "./api/resources/beta/client/Client.js";
import { Cache } from "./api/resources/cache/client/Client.js";

export declare namespace ImageKitClient {
    export interface Options {
        environment?: core.Supplier<environments.ImageKitEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class ImageKitClient {
    protected readonly _options: ImageKitClient.Options;
    protected _files: Files | undefined;
    protected _customMetadataFields: CustomMetadataFields | undefined;
    protected _assets: Assets | undefined;
    protected _folders: Folders | undefined;
    protected _accounts: Accounts | undefined;
    protected _beta: Beta | undefined;
    protected _cache: Cache | undefined;

    constructor(_options: ImageKitClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "imagekit",
                    "X-Fern-SDK-Version": "6.0.1",
                    "User-Agent": "imagekit/6.0.1",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }

    public get customMetadataFields(): CustomMetadataFields {
        return (this._customMetadataFields ??= new CustomMetadataFields(this._options));
    }

    public get assets(): Assets {
        return (this._assets ??= new Assets(this._options));
    }

    public get folders(): Folders {
        return (this._folders ??= new Folders(this._options));
    }

    public get accounts(): Accounts {
        return (this._accounts ??= new Accounts(this._options));
    }

    public get beta(): Beta {
        return (this._beta ??= new Beta(this._options));
    }

    public get cache(): Cache {
        return (this._cache ??= new Cache(this._options));
    }
}
