/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ImageKitEnvironment = {
    Default: "https://api.imagekit.io",
} as const;

export type ImageKitEnvironment = typeof ImageKitEnvironment.Default;
