// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asTextContentResult } from 'imagekit-api-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import ImageKit from '@imagekit/nodejs';

export const metadata: Metadata = {
  resource: 'accounts.origins',
  operation: 'write',
  tags: [],
  httpMethod: 'delete',
  httpPath: '/v1/accounts/origins/{id}',
  operationId: 'delete-origin',
};

export const tool: Tool = {
  name: 'delete_accounts_origins',
  description:
    '**Note:** This API is currently in beta.  \nPermanently removes the origin identified by `id`. If the origin is in use by any URL‑endpoints, the API will return an error.\n',
  inputSchema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
        description:
          'Unique identifier for the origin. This is generated by ImageKit when you create a new origin.',
      },
    },
    required: ['id'],
  },
  annotations: {
    idempotentHint: true,
  },
};

export const handler = async (client: ImageKit, args: Record<string, unknown> | undefined) => {
  const { id, ...body } = args as any;
  const response = await client.accounts.origins.delete(id).asResponse();
  return asTextContentResult(await response.text());
};

export default { metadata, tool, handler };
