/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FoldersCopyResponse {
    /** Unique identifier of the bulk job. This can be used to check the status of the bulk job. */
    jobId?: string;
}
