name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm i -g yarn
        yarn install
        yarn test
    - name: Publish Code Coverage to codecove.io
      run: |
        yarn i -g nyc codecov 
        yarn run report-coverage        
      env:
        CI: true
